=== santosghost/projetBaseDeDonn-es/test1.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT schemaea ANY>
<!ELEMENT entite (nomentite?,propriete*)>
<!ELEMENT association (nomasso?,entasso*,propriete*)>
<!ELEMENT nomentite (#PCDATA)>
<!ELEMENT propriete (#PCDATA)>
<!ELEMENT entasso EMPTY>
<!ELEMENT nomasso (#PCDATA)>
<!ATTLIST entite
	id CDATA #REQUIRED>
<!ATTLIST association
	id CDATA #REQUIRED>

<!ATTLIST propriete
	cle CDATA #IMPLIED
	type CDATA #REQUIRED
	longueur CDATA #IMPLIED >

<!ATTLIST entasso
	role CDATA #REQUIRED
	cardmin	CDATA #REQUIRED
	cardmax	CDATA #REQUIRED
	source CDATA #REQUIRED>

=== santosghost/projetBaseDeDonn-es/test1.xml
<?xml version="1.0"?>
<!DOCTYPE schemaea SYSTEM "test1.dtd">
	<schemaea>
		<entite id="e1">
			<nomentite>E1</nomentite>
			<propriete cle="oui" type="entier">p1</propriete>
			<propriete cle="non" type="chaine" longueur="20">p2</propriete>
		</entite>
		<entite id="e2">
			<nomentite>E2</nomentite>
			<propriete cle="oui" type="entier">p3</propriete>
			<propriete cle="non" type="chaine" longueur="10">p4</propriete>
			<propriete cle="non" type="chaine" longueur="30">p5</propriete>
		</entite> 
		<association id="a1">
			<nomasso>A1</nomasso>
			<entasso role="r1" cardmin="1" cardmax="N" source="e1"/>
			<entasso role="r2" cardmin="1" cardmax="N" source="e2"/>
			<propriete type="entier">pa1</propriete>
		</association>
</schemaea>
